# Generated by Django 3.1.5 on 2021-01-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='cues',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='questions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
